version: '3.8'

services:
  # 1. Banco de Dados PostgreSQL
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD_POSTGRES}
      POSTGRES_DB: ${DB_NAME_AUTH}

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    deploy: # Otimização de recursos
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  # 2. COnsul Server
  consul-server:
    image: consul:1.15.4
    container_name: consul-server
    command: agent -server -bootstrap-expect=1 -ui -node=server1 -client=0.0.0.0
    ports:
      - "8500:8500"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 350m
        reservations:
          cpus: '0.5'
          memory: 256m


  # 3. MS de Autenticação
  ms-auth:
    build:
      context: ./ms-auth
      dockerfile: Dockerfile
    container_name: ms-auth
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/ms_auth

  # 4. MS do Catálogo
  ms-catalog:
    build:
      context: ./ms-catalog
      dockerfile: Dockerfile
    container_name: ms-catalog

  # 5. MS das Sessões
  ms-sessions:
    build:
      context: ./ms-sessions
      dockerfile: Dockerfile
    container_name: ms-sessions

  # 6. API Gateway
  ms-gateway:
    build:
      context: ./ms-gateway
      dockerfile: Dockerfile
    container_name: ms-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul-server
      - SPRING_CLOUD_CONSUL_PORT=8500
      - JWT_SECRET=${JWT_SECRET}
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    depends_on:
      - consul-server
      - ms-auth
      - ms-catalog
      - ms-sessions

  # 7. Frontend (Nginx)
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8085:80"
    volumes:
      - ./frontend/http:/usr/share/nginx/html
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M

volumes:
  postgres_data: